---
title: "Task2"
author: "Vladyslav Kushnir"
date: "10/01/2024"
format:
  html:
    embed-resources: true
editor: source
---

## 1 Create the random vector
```{r}
# Create the random vector
v <- rnorm(50)

# Print 10th item
print(v[10])

# Print items from 10th to 20th (including 20th)
print(v[10:20])

# Print 10 items starting from 5th
print(v[5:14])

# Print all items bigger than 0
print(v[v > 0])

# Print last 5 items
print(v[(length(v)-4):length(v)])
```
## 2 Create the data frame
```{r}
df <- data.frame(a = rnorm(50), b = 1:50, 
                 cc = sample(letters, 50, replace = TRUE))

# Print last 10 rows
print(tail(df, 10))

# Print 15th item of column `cc`
print(df$cc[15])

# Subset columns `a` and `b` and rows from 10th to 20th (including 20th)
print(df[10:20, c("a", "b")])

# Create a new vector from column `b`
new_vector <- df$b
print(new_vector)
```
## 3 Create the random vector with NA values
```{r}
v_na <- rnorm(30)
num_na <- sample(10, 1)
v_na[sample(30, num_na)] <- NA

# Print all not NA items
print(v_na[!is.na(v_na)])

# Find how many NA values the vector has
na_count <- sum(is.na(v_na))
print(na_count)

# Find min, max, and mean for the vector
v_na_min <- min(v_na, na.rm = TRUE)
v_na_max <- max(v_na, na.rm = TRUE)
v_na_mean <- mean(v_na, na.rm = TRUE)

print(c(min = v_na_min, max = v_na_max, mean = v_na_mean))
```


